using System.Collections.Generic;
using System.Linq;
using WoWClassicNews.Models;

namespace WoWClassicNews.DataAccess.DataSeeder
{
    public class WarriorClassSeeder
    {
        public static List<WarcraftClassSpecification> Setup(List<TalentIcon> icons)
        {
            var armsSpec = new List<Talent>
            {
                new Talent { TalentName = "Improved Herioc Strike", ColumnIndex = 0, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "ability_rogue_ambush").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the cost of your Heroic Strike ability by 1 rage point." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the cost of your Heroic Strike ability by 2 rage point." },
                        new TalentRank { RankNo = 3, RankDescription = "Reduces the cost of your Heroic Strike ability by 3 rage point." }
                } },
                new Talent { TalentName = "Deflection", ColumnIndex = 1, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "ability_parry").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your Parry chance by 1%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your Parry chance by 2%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your Parry chance by 3%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your Parry chance by 4%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your Parry chance by 5%." }
                } },
                new Talent { TalentName = "Improved Rend", ColumnIndex = 2, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "ability_gouge").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the bleed damage done by your Rend ability by 15%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the bleed damage done by your Rend ability by 25%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the bleed damage done by your Rend ability by 35%" }
                } },
                new Talent { TalentName = "Improved Charge", ColumnIndex = 0, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "ability_warrior_charge").Id,
                     TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the amount of rage generated by your Charge ability by 3." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the amount of rage generated by your Charge ability by 6." }
                } },
                new Talent { TalentName = "Tactical Mastery", ColumnIndex = 1, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_nature_enchantarmor").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "You retain up to 5 of your rage points when you change stances." },
                        new TalentRank { RankNo = 2, RankDescription = "You retain up to 10 of your rage points when you change stances." },
                        new TalentRank { RankNo = 3, RankDescription = "You retain up to 15 of your rage points when you change stances." },
                        new TalentRank { RankNo = 4, RankDescription = "You retain up to 20 of your rage points when you change stances." },
                        new TalentRank { RankNo = 5, RankDescription = "You retain up to 25 of your rage points when you change stances." }
                } },
                new Talent { TalentName = "Improved Thunder Clap", ColumnIndex = 3, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "ability_thunderclap").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the cost of your Thunder Clap ability by 1 rage point." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the cost of your Thunder Clap ability by 2 rage point." },
                        new TalentRank { RankNo = 3, RankDescription = "Reduces the cost of your Thunder Clap ability by 4 rage point." }
                } },
                new Talent { TalentName = "Improved Overpower", ColumnIndex = 0, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "inv_sword_05").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the critical strike chance of your Overpower ability by 25%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the critical strike chance of your Overpower ability by 50%." }
                } },
                new Talent { TalentName = "Anger Management", ColumnIndex = 1, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_holy_blessingofstamina").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the time required for your rage to decay while out of combat by 30%." }
                } },
                new Talent { TalentName = "Deep Wounds", ColumnIndex = 2, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "ability_backstab").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Your critical strikes cause the opponent to bleed, dealing 20% of your melee weapomn's average damage over 12 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Your critical strikes cause the opponent to bleed, dealing 40% of your melee weapomn's average damage over 12 sec." },
                        new TalentRank { RankNo = 3, RankDescription = "Your critical strikes cause the opponent to bleed, dealing 60% of your melee weapomn's average damage over 12 sec." }
                } },
                new Talent { TalentName = "Two-Handed Weapon Specialization", ColumnIndex = 1, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "inv_axe_09").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the damage you deal with two-handed melee weapons by 1%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the damage you deal with two-handed melee weapons by 2%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the damage you deal with two-handed melee weapons by 3%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases the damage you deal with two-handed melee weapons by 4%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases the damage you deal with two-handed melee weapons by 5%." }
                } },
                new Talent { TalentName = "Impale", ColumnIndex = 2, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "ability_searingarrow").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 10%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the critical strike damage bonus of your abilities in Battle, Defensive, and Berserker stance by 20%." }
                } },
                new Talent { TalentName = "Axe Specialization", ColumnIndex = 0, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "inv_axe_06").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your chance to get a critical strike with Axes by 1%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your chance to get a critical strike with Axes by 2%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your chance to get a critical strike with Axes by 3%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your chance to get a critical strike with Axes by 4%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your chance to get a critical strike with Axes by 5%." }
                } },
                new Talent { TalentName = "Sweeping Strikes", ColumnIndex = 1, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "ability_rogue_slicedice").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Your next 5 melee attacks strike an additional nearby opponent." }
                } },
                new Talent { TalentName = "Mace Specialization", ColumnIndex = 2, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "inv_mace_01").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Gives you a 1% chance to stun your target for 3 sec with a Mace." },
                        new TalentRank { RankNo = 2, RankDescription = "Gives you a 2% chance to stun your target for 3 sec with a Mace." },
                        new TalentRank { RankNo = 3, RankDescription = "Gives you a 3% chance to stun your target for 3 sec with a Mace." },
                        new TalentRank { RankNo = 4, RankDescription = "Gives you a 4% chance to stun your target for 3 sec with a Mace." },
                        new TalentRank { RankNo = 5, RankDescription = "Gives you a 5% chance to stun your target for 3 sec with a Mace." }
                } },
                new Talent { TalentName = "Sword Specialization", ColumnIndex = 3, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "inv_sword_27").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Gives you a 1% chance to get an extra attack on the same target after dealing damage with your Sword." },
                        new TalentRank { RankNo = 2, RankDescription = "Gives you a 2% chance to get an extra attack on the same target after dealing damage with your Sword." },
                        new TalentRank { RankNo = 3, RankDescription = "Gives you a 3% chance to get an extra attack on the same target after dealing damage with your Sword." },
                        new TalentRank { RankNo = 4, RankDescription = "Gives you a 4% chance to get an extra attack on the same target after dealing damage with your Sword." },
                        new TalentRank { RankNo = 5, RankDescription = "Gives you a 5% chance to get an extra attack on the same target after dealing damage with your Sword." }
                } },
                new Talent { TalentName = "Polearm Specialization", ColumnIndex = 0, RowIndex = 5, TalentIconId = icons.First(i => i.FileName == "inv_weapon_halbard_01").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your chance to get a critical strike with Polearms by 1%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your chance to get a critical strike with Polearms by 2%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your chance to get a critical strike with Polearms by 3%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your chance to get a critical strike with Polearms by 4%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your chance to get a critical strike with Polearms by 5%." }
                 } },
                new Talent { TalentName = "Improved Hamstring", ColumnIndex = 2, RowIndex = 5, TalentIconId = icons.First(i => i.FileName == "ability_shockwave").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Gives your Hamstring ability a 5% chance to immobilize the target for 5 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Gives your Hamstring ability a 10% chance to immobilize the target for 5 sec." },
                        new TalentRank { RankNo = 3, RankDescription = "Gives your Hamstring ability a 15% chance to immobilize the target for 5 sec." }
                 } },
                new Talent { TalentName = "Mortal Strike", ColumnIndex = 1, RowIndex = 6, TalentIconId = icons.First(i => i.FileName == "ability_warrior_savageblow").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "A vicious strike that deals weapon damage plus 85 and wounds the target, reducing the effectiveness of any healing by 50% for 10 sec." }
                 } }
            };

            var furySpec = new List<Talent>
            {
                new Talent { TalentName = "Booming Voice", ColumnIndex = 1, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "spell_nature_purge").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 10%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 20%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 30%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 40%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases the area of effect and duration of your Battle Shout and Demoralizing Shout by 50%." }
                } },
                new Talent { TalentName = "Cruelty", ColumnIndex = 2, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "ability_rogue_eviscerate").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your chance to get a critical strike with melee weapons by 1%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your chance to get a critical strike with melee weapons by 2%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your chance to get a critical strike with melee weapons by 3%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your chance to get a critical strike with melee weapons by 4%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your chance to get a critical strike with melee weapons by 5%." }
                } },
                new Talent { TalentName = "Improved Demoralizing Shout", ColumnIndex = 1, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "ability_warrior_warcry").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the melee attack power reduction of your Demoralizing Shout by 8%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the melee attack power reduction of your Demoralizing Shout by 16%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the melee attack power reduction of your Demoralizing Shout by 24%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases the melee attack power reduction of your Demoralizing Shout by 32%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases the melee attack power reduction of your Demoralizing Shout by 40%." }
                } },
                new Talent { TalentName = "Unbridled Wrath", ColumnIndex = 2, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_nature_stoneclawtotem").Id,
                     TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Gives you a 8% chance to generate an additional Rage point when you deal melee damage with a weapon." },
                        new TalentRank { RankNo = 2, RankDescription = "Gives you a 16% chance to generate an additional Rage point when you deal melee damage with a weapon." },
                        new TalentRank { RankNo = 3, RankDescription = "Gives you a 24% chance to generate an additional Rage point when you deal melee damage with a weapon." },
                        new TalentRank { RankNo = 4, RankDescription = "Gives you a 32% chance to generate an additional Rage point when you deal melee damage with a weapon." },
                        new TalentRank { RankNo = 5, RankDescription = "Gives you a 40% chance to generate an additional Rage point when you deal melee damage with a weapon." }
                } },
                new Talent { TalentName = "Improved Cleave", ColumnIndex = 0, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "ability_warrior_cleave").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the bonus damage done by your Cleave ability by 40%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the bonus damage done by your Cleave ability by 80%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the bonus damage done by your Cleave ability by 120%." }
                } },
                new Talent { TalentName = "Piercing Howl", ColumnIndex = 1, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_shadow_deathscream").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Causes all enemies near the warrior to be dazed reducing movement speed by 50% for 6 sec." }
                } },
                new Talent { TalentName = "Blood Craze", ColumnIndex = 2, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_shadow_summonimp").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Regenerates 1% of your total Health over 6 sec after being the victim of a critical strike." },
                        new TalentRank { RankNo = 2, RankDescription = "Regenerates 2% of your total Health over 6 sec after being the victim of a critical strike." },
                        new TalentRank { RankNo = 3, RankDescription = "Regenerates 3% of your total Health over 6 sec after being the victim of a critical strike." }
                } },
                new Talent { TalentName = "Improved Battle Shout", ColumnIndex = 3, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "ability_warrior_battleshout").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the melee attack power bonus of your Battle Shout by 5%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the melee attack power bonus of your Battle Shout by 10%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the melee attack power bonus of your Battle Shout by 15%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases the melee attack power bonus of your Battle Shout by 20%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases the melee attack power bonus of your Battle Shout by 25%." }
                } },
                new Talent { TalentName = "Dual Wield Specialization", ColumnIndex = 0, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "ability_dualwield").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the damage done by your offhand weapon by 5%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the damage done by your offhand weapon by 10%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the damage done by your offhand weapon by 15%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases the damage done by your offhand weapon by 20%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases the damage done by your offhand weapon by 25%." }
                } },
                new Talent { TalentName = "Improved Execute", ColumnIndex = 1, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "inv_sword_48").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the Rage cost of your Execute ability by 2." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the Rage cost of your Execute ability by 5." }
                } },
                new Talent { TalentName = "Enrage", ColumnIndex = 2, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "spell_shadow_unholyfrenzy").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Gives you a 5% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike." },
                        new TalentRank { RankNo = 2, RankDescription = "Gives you a 10% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike." },
                        new TalentRank { RankNo = 3, RankDescription = "Gives you a 15% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike." },
                        new TalentRank { RankNo = 4, RankDescription = "Gives you a 20% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike." },
                        new TalentRank { RankNo = 5, RankDescription = "Gives you a 25% melee damage bonus for 12 sec up to a maximum of 12 swings after being the victim of a critical strike." }
                } },
                new Talent { TalentName = "Improved Slam", ColumnIndex = 0, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "ability_warrior_decisivestrike").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Decreases the casting time of your Slam ability by 0.1 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Decreases the casting time of your Slam ability by 0.2 sec." },
                        new TalentRank { RankNo = 3, RankDescription = "Decreases the casting time of your Slam ability by 0.3 sec." },
                        new TalentRank { RankNo = 4, RankDescription = "Decreases the casting time of your Slam ability by 0.4 sec." },
                        new TalentRank { RankNo = 5, RankDescription = "Decreases the casting time of your Slam ability by 0.5 sec." }
                } },
                new Talent { TalentName = "Death Wish", ColumnIndex = 1, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "spell_shadow_deathpact").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "When activated, increases your physical damage by 20% and makes you immune to fear effects, but lowers your armor and all resistance by 20%. Lasts 30 sec." }
                } },
                new Talent { TalentName = "Improved Intercept", ColumnIndex = 3, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "ability_rogue_sprint").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the cooldown of your Intercept ability by 5 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the cooldown of your Intercept ability by 10 sec." }
                } },
                new Talent { TalentName = "Improved Berserker Rage", ColumnIndex = 2, RowIndex = 5, TalentIconId = icons.First(i => i.FileName == "spell_nature_ancestralguardian").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "The Berserker Rage ability will generate 5 rage when used." },
                        new TalentRank { RankNo = 2, RankDescription = "The Berserker Rage ability will generate 10 rage when used." }
                } },
                new Talent { TalentName = "Flurry", ColumnIndex = 2, RowIndex = 5, TalentIconId = icons.First(i => i.FileName == "ability_warrior_decisivestrike").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your attack speed by 10% for your next 3 swings after dealing a melee critical strike." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your attack speed by 15% for your next 3 swings after dealing a melee critical strike." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your attack speed by 20% for your next 3 swings after dealing a melee critical strike." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your attack speed by 25% for your next 3 swings after dealing a melee critical strike." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your attack speed by 30% for your next 3 swings after dealing a melee critical strike." }
                } },
                new Talent { TalentName = "Bloodthirst", ColumnIndex = 1, RowIndex = 6, TalentIconId = icons.First(i => i.FileName == "spell_nature_bloodlust").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Instantly attack the target causing damage equal to 45% of your attack power. In addtion, the next 5 successful melee attacks will restore 10 health. This effect lasts 8 sec." }
                } }
            };

            var protectionSpec = new List<Talent>
            {
                new Talent { TalentName = "Shield Specialization", ColumnIndex = 1, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "inv_shield_06").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your chance to block attacks with a shield by 1% and has a 20% chance to generate 1 rage when a block occurs." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your chance to block attacks with a shield by 2% and has a 40% chance to generate 1 rage when a block occurs." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your chance to block attacks with a shield by 3% and has a 60% chance to generate 1 rage when a block occurs." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your chance to block attacks with a shield by 4% and has a 80% chance to generate 1 rage when a block occurs." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your chance to block attacks with a shield by 5% and has a 100% chance to generate 1 rage when a block occurs." }
                } },
                new Talent { TalentName = "Anticipation", ColumnIndex = 2, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "spell_nature_mirrorimage").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your Defense skill by 2." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your Defense skill by 4." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your Defense skill by 6." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your Defense skill by 8." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your Defense skill by 10." }
                } },
                new Talent { TalentName = "Improved Bloodrage", ColumnIndex = 0, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "ability_racial_bloodrage").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the instant Rage generated by your Bloodrage ability by 2." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the instant Rage generated by your Bloodrage ability by 5." }
                } },
                new Talent { TalentName = "Toughness", ColumnIndex = 2, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_holy_devotion").Id,
                     TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your armor value from items by 2%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your armor value from items by 4%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your armor value from items by 6%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your armor value from items by 8%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your armor value from items by 10%." }
                } },
                new Talent { TalentName = "Iron Will", ColumnIndex = 3, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_magic_magearmor").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your chance to resist Stun and Charm effects by an additional 3%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your chance to resist Stun and Charm effects by an additional 3%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your chance to resist Stun and Charm effects by an additional 3%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your chance to resist Stun and Charm effects by an additional 3%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your chance to resist Stun and Charm effects by an additional 3%." }
                } },
                new Talent { TalentName = "Last Stand", ColumnIndex = 0, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_holy_ashestoashes").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "When activated, this ability temporarily grants you a 30% of your maximum hit points for 20 seconds. After the effect expires, the hit points are lost." }
                } },
                new Talent { TalentName = "Improved Shield Block", ColumnIndex = 1, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "ability_defend").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Allows your Shield Block ability to block an additional attack and increases the duration by 0.5 second." },
                        new TalentRank { RankNo = 2, RankDescription = "Allows your Shield Block ability to block an additional attack and increases the duration by 1 second." },
                        new TalentRank { RankNo = 3, RankDescription = "Allows your Shield Block ability to block an additional attack and increases the duration by 2 second." }
                } },
                new Talent { TalentName = "Improved Revenge", ColumnIndex = 2, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "ability_warrior_revenge").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Gives your Revenge ability a 15% chance to stun the target for 3 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Gives your Revenge ability a 30% chance to stun the target for 3 sec." },
                        new TalentRank { RankNo = 3, RankDescription = "Gives your Revenge ability a 45% chance to stun the target for 3 sec." }
                } },
                new Talent { TalentName = "Defiance", ColumnIndex = 3, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "ability_warrior_innerrage").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the threat generated by your attacks by 3% while in Defensive Stance." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the threat generated by your attacks by 6% while in Defensive Stance." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the threat generated by your attacks by 9% while in Defensive Stance." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases the threat generated by your attacks by 12% while in Defensive Stance." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases the threat generated by your attacks by 15% while in Defensive Stance." }
                } },
                new Talent { TalentName = "Improved Sunder Armour", ColumnIndex = 0, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "ability_warrior_sunder").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the cost of your Sunder Armor ability by 1 rage point." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the cost of your Sunder Armor ability by 2 rage points." },
                        new TalentRank { RankNo = 3, RankDescription = "Reduces the cost of your Sunder Armor ability by 3 rage points." }
                } },
                new Talent { TalentName = "Improved Disarm", ColumnIndex = 1, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "ability_warrior_disarm").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the duration of your Disarm ability by 1 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the duration of your Disarm ability by 2 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the duration of your Disarm ability by 3 sec." }
                } },
                new Talent { TalentName = "Improved Taunt", ColumnIndex = 2, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "spell_nature_reincarnation").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the cooldown of your Taunt ability by 1 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the cooldown of your Taunt ability by 2 sec." }
                } },
                new Talent { TalentName = "Improved Shield Wall", ColumnIndex = 2, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "ability_warrior_shieldwall").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the effect duration of your Shield Wall ability by 3 secs." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the effect duration of your Shield Wall ability by 5 secs." }
                } },
                new Talent { TalentName = "Concussion Blow", ColumnIndex = 1, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "ability_thunderbolt").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Stuns the opponent for 5 sec." }
                } },
                new Talent { TalentName = "Improved Shield Bash", ColumnIndex = 2, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "ability_warrior_shieldbash").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Gives your Shield Bash ability a 50% chance to silence the target for 3 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Gives your Shield Bash ability a 100% chance to silence the target for 3 sec." }
                 } },
                new Talent { TalentName = "One-Handed Weapon Specialization", ColumnIndex = 2, RowIndex = 5, TalentIconId = icons.First(i => i.FileName == "inv_sword_20").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the damage you deal with One-Handed Melee weapons by 2%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the damage you deal with One-Handed Melee weapons by 4%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the damage you deal with One-Handed Melee weapons by 6%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases the damage you deal with One-Handed Melee weapons by 8%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases the damage you deal with One-Handed Melee weapons by 10%." }
                } },
                new Talent { TalentName = "Shield Slam", ColumnIndex = 1, RowIndex = 6, TalentIconId = icons.First(i => i.FileName == "inv_shield_05").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Slam the target with your shield, causing 225 to 236 damage, modified by your shield block value, and has a 50% chance of dispelling 1 magic effect on the target. Also causes a high amount of threat." }
                 } }
            };

            return new List<WarcraftClassSpecification> {
                new WarcraftClassSpecification { SpecificationName = "Arms", SpecificationIndex = 0, SpecificationIcon = "ability_rogue_eviscerate.jpg", Talents = armsSpec },
                new WarcraftClassSpecification { SpecificationName = "Fury", SpecificationIndex = 1, SpecificationIcon = "ability_warrior_innerrage.jpg", Talents = furySpec },
                new WarcraftClassSpecification { SpecificationName = "Protection", SpecificationIndex = 2, SpecificationIcon = "ability_warrior_defensivestance.jpg", Talents = protectionSpec }
            };
        }

        public static void SetupTalentRequirements(List<WarcraftClassSpecification> wcs)
        {
            var armsTalents = wcs[0].Talents;
            var furyTalents = wcs[1].Talents;
            var protectionTalents = wcs[2].Talents;

            armsTalents.First(t => t.TalentName == "Deep Wounds").RequiredTalent = armsTalents.First(t => t.TalentName == "Improved Rend");
            armsTalents.First(t => t.TalentName == "Anger Management").RequiredTalent = armsTalents.First(t => t.TalentName == "Tactical Mastery");
            armsTalents.First(t => t.TalentName == "Impale").RequiredTalent = armsTalents.First(t => t.TalentName == "Deep Wounds");
            armsTalents.First(t => t.TalentName == "Mortal Strike").RequiredTalent = armsTalents.First(t => t.TalentName == "Sweeping Strikes");

            furyTalents.First(t => t.TalentName == "Flurry").RequiredTalent = furyTalents.First(t => t.TalentName == "Enrage");
            furyTalents.First(t => t.TalentName == "Bloodthirst").RequiredTalent = furyTalents.First(t => t.TalentName == "Death Wish");

            protectionTalents.First(t => t.TalentName == "Improved Shield Block").RequiredTalent = protectionTalents.First(t => t.TalentName == "Shield Specialization");
            protectionTalents.First(t => t.TalentName == "Shield Slam").RequiredTalent = protectionTalents.First(t => t.TalentName == "Concussion Blow");
        }
    }
}
