// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WoWClassicTalentCalculator.DataAccess;

namespace WoWClassicTalentCalculator.Migrations
{
    [DbContext(typeof(TalentCalculatorContext))]
    [Migration("20171127145101_AddedOrderColumnToClasses")]
    partial class AddedOrderColumnToClasses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WoWClassicTalentCalculator.Models.Talent", b =>
                {
                    b.Property<int>("TalentId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ColumnIndex");

                    b.Property<int>("NoOfRanks");

                    b.Property<int>("RowIndex");

                    b.Property<string>("TalentDescription");

                    b.Property<string>("TalentName");

                    b.Property<int>("WarcraftClassSpecificationId");

                    b.HasKey("TalentId");

                    b.HasIndex("WarcraftClassSpecificationId");

                    b.ToTable("Talents");
                });

            modelBuilder.Entity("WoWClassicTalentCalculator.Models.WarcraftClass", b =>
                {
                    b.Property<int>("WarcraftClassId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClassName");

                    b.Property<int>("Order");

                    b.HasKey("WarcraftClassId");

                    b.ToTable("WarcraftClasses");
                });

            modelBuilder.Entity("WoWClassicTalentCalculator.Models.WarcraftClassSpecification", b =>
                {
                    b.Property<int>("WarcraftClassSpecificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SpecificationIndex");

                    b.Property<string>("SpecificationName");

                    b.Property<int>("WarcraftClassId");

                    b.HasKey("WarcraftClassSpecificationId");

                    b.HasIndex("WarcraftClassId");

                    b.ToTable("WarcraftClassSpecifications");
                });

            modelBuilder.Entity("WoWClassicTalentCalculator.Models.Talent", b =>
                {
                    b.HasOne("WoWClassicTalentCalculator.Models.WarcraftClassSpecification")
                        .WithMany("Talents")
                        .HasForeignKey("WarcraftClassSpecificationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WoWClassicTalentCalculator.Models.WarcraftClassSpecification", b =>
                {
                    b.HasOne("WoWClassicTalentCalculator.Models.WarcraftClass")
                        .WithMany("WarcraftClassSpecifications")
                        .HasForeignKey("WarcraftClassId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
