using System.Collections.Generic;
using System.Linq;
using VanillaReborn.Models;

namespace VanillaReborn.DataAccess.DataSeeder
{
    public class PriestClassSeeder
    {
        public static List<WarcraftClassSpecification> Setup(List<TalentIcon> icons)
        {
            var disciplineSpec = new List<Talent>
            {
                new Talent { TalentName = "Unbreakable Will", ColumnIndex = 1, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "spell_magic_magearmor").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your chance to resist Stun, Fear and Silence effects by an additional 3%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your chance to resist Stun, Fear and Silence effects by an additional 6%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your chance to resist Stun, Fear and Silence effects by an additional 9%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your chance to resist Stun, Fear and Silence effects by an additional 12%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your chance to resist Stun, Fear and Silence effects by an additional 15%." }
                } },
                new Talent { TalentName = "Wand Specialization", ColumnIndex = 2, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "inv_wand_01").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your damage with Wands by 5%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your damage with Wands by 10%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your damage with Wands by 15%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your damage with Wands by 20%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your damage with Wands by 25%." }
                } },
                new Talent { TalentName = "Silent Resolve", ColumnIndex = 0, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_nature_manaregentotem").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the threat generated by your spells by 4%." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the threat generated by your spells by 8%." },
                        new TalentRank { RankNo = 3, RankDescription = "Reduces the threat generated by your spells by 12%." },
                        new TalentRank { RankNo = 4, RankDescription = "Reduces the threat generated by your spells by 16%." },
                        new TalentRank { RankNo = 5, RankDescription = "Reduces the threat generated by your spells by 20%." }
                } },
                new Talent { TalentName = "Improved Power Word: Fortitude", ColumnIndex = 1, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_holy_wordfortitude").Id,
                     TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the effects of your Power Word: Fortitude and Prayer of Fortitude spells by 15%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the effects of your Power Word: Fortitude and Prayer of Fortitude spells by 30%." }
                } },
                new Talent { TalentName = "Improved Power Word: Shield", ColumnIndex = 2, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_holy_powerwordshield").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the damage absorbed by your Power Word: Shield by 5%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the damage absorbed by your Power Word: Shield by 10%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the damage absorbed by your Power Word: Shield by 15%." }
                } },
                new Talent { TalentName = "Martyrdom", ColumnIndex = 3, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_nature_tranquility").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Allows 5% of your Mana regeneration to continue while casting." },
                        new TalentRank { RankNo = 2, RankDescription = "Allows 5% of your Mana regeneration to continue while casting." }
                } },
                new Talent { TalentName = "Inner Focus", ColumnIndex = 1, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_frost_windwalkon").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "When activated, reduces the Mana cost of your next spell by 100% and increases its critical effect chance by 25% if it is capable of a critical effect." }
                } },
                new Talent { TalentName = "Meditation", ColumnIndex = 2, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_nature_sleep").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Allows 5% of your Mana regeneration to continue while casting." },
                        new TalentRank { RankNo = 2, RankDescription = "Allows 10% of your Mana regeneration to continue while casting." },
                        new TalentRank { RankNo = 3, RankDescription = "Allows 15% of your Mana regeneration to continue while casting." }
                } },
                new Talent { TalentName = "Improved Inner Fire", ColumnIndex = 0, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "spell_holy_innerfire").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the Armor bonus of your Inner Fire spell by 10%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the Armor bonus of your Inner Fire spell by 20%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the Armor bonus of your Inner Fire spell by 30%." }
                } },
                new Talent { TalentName = "Mental Agility", ColumnIndex = 1, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "ability_hibernation").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Decreases the mana lost per point of damage taken when Mana Shield is active by 10%." },
                        new TalentRank { RankNo = 2, RankDescription = "Decreases the mana lost per point of damage taken when Mana Shield is active by 20%." }
                } },
                new Talent { TalentName = "Improved Mana Burn", ColumnIndex = 3, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "spell_shadow_manaburn").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the casting time of your Mana Burn spell by 0.25 secs." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the casting time of your Mana Burn spell by 0.5 sec." }
                } },
                new Talent { TalentName = "Mental Strength", ColumnIndex = 1, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "spell_nature_enchantarmor").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your maximum Mana by 2%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your maximum Mana by 4%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your maximum Mana by 6%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your maximum Mana by 8%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your maximum Mana by 10%." }
                } },
                new Talent { TalentName = "Divine Spirit", ColumnIndex = 2, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "spell_holy_divinespirit").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Holy power infuses the target, increasing their Spirit by 17 for 30 min." }
                } },
                new Talent { TalentName = "Force of Will", ColumnIndex = 2, RowIndex = 5, TalentIconId = icons.First(i => i.FileName == "spell_nature_slowingtotem").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your spell damage by 1% and the critical strike chance of your offensive spells by 1%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your spell damage by 1% and the critical strike chance of your offensive spells by 2%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your spell damage by 1% and the critical strike chance of your offensive spells by 3%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your spell damage by 1% and the critical strike chance of your offensive spells by 4%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your spell damage by 1% and the critical strike chance of your offensive spells by 5%." }
                } },
                new Talent { TalentName = "Power Infusion", ColumnIndex = 1, RowIndex = 6, TalentIconId = icons.First(i => i.FileName == "spell_holy_powerinfusion").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Infuses the target with power, increasing their spell damage and healing by 20%. Lasts 15 sec." }
                 } }
            };

            var holySpec = new List<Talent>
            {
                new Talent { TalentName = "Healing Focus", ColumnIndex = 0, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "spell_holy_healingfocus").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Gives you a 35% chance to avoid interruption caused by damage while casting any healing spell." },
                        new TalentRank { RankNo = 2, RankDescription = "Gives you a 70% chance to avoid interruption caused by damage while casting any healing spell." }
                } },
                new Talent { TalentName = "Improved Renew", ColumnIndex = 1, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "spell_holy_renew").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the amount healed by your Renew spell by 5%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the amount healed by your Renew spell by 10%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the amount healed by your Renew spell by 15%." }
                } },
                new Talent { TalentName = "Holy Specialization", ColumnIndex = 2, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "spell_holy_sealofsalvation").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the critical effect chance of your Holy spells by 1%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the critical effect chance of your Holy spells by 2%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the critical effect chance of your Holy spells by 3%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases the critical effect chance of your Holy spells by 4%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases the critical effect chance of your Holy spells by 5%." }
                } },
                new Talent { TalentName = "Spell Warding", ColumnIndex = 1, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_holy_spellwarding").Id,
                     TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases all spell damage taken by 2%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases all spell damage taken by 4%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases all spell damage taken by 6%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases all spell damage taken by 8%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases all spell damage taken by 10%." }
                } },
                new Talent { TalentName = "Divine Fury", ColumnIndex = 2, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_holy_sealofwrath").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.1%." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.2%." },
                        new TalentRank { RankNo = 3, RankDescription = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.3%." },
                        new TalentRank { RankNo = 4, RankDescription = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.4%." },
                        new TalentRank { RankNo = 5, RankDescription = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by 0.5%." }
                } },
                new Talent { TalentName = "Holy Nova", ColumnIndex = 0, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_holy_holynova").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Causes an explosion of holy light around the caster, causing 28 to 33 Holy damage to all enemy targets within 10 yards and healing all party members within 10 yards for 52 to 61. These effects cause no threat." }
                } },
                new Talent { TalentName = "Blessed Recovery", ColumnIndex = 1, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_holy_blessedrecovery").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "After being struck by a melee or ranged critical hit, heal 8% of the damage taken over 6 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "After being struck by a melee or ranged critical hit, heal 16% of the damage taken over 6 sec." },
                        new TalentRank { RankNo = 3, RankDescription = "After being struck by a melee or ranged critical hit, heal 25% of the damage taken over 6 sec." }
                } },
                new Talent { TalentName = "Inspiration", ColumnIndex = 3, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_holy_layonhands").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your target's armor by 8% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your target's armor by 16% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your target's armor by 25% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell." }
                } },
                new Talent { TalentName = "Holy Reach", ColumnIndex = 0, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "spell_holy_purify").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing and Holy Nova spells by 10%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing and Holy Nova spells by 20%." }
                } },
                new Talent { TalentName = "Improved Healing", ColumnIndex = 1, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "spell_holy_heal02").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the Mana cost of your Less Heal, Heal, and Greater Heal spells by 5%." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the Mana cost of your Less Heal, Heal, and Greater Heal spells by 10%." },
                        new TalentRank { RankNo = 3, RankDescription = "Reduces the Mana cost of your Less Heal, Heal, and Greater Heal spells by 15%." }
                } },
                new Talent { TalentName = "Searing Light", ColumnIndex = 2, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "spell_holy_searinglightpriest").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the damage of your Smite and Holy Fire spells by 5%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the damage of your Smite and Holy Fire spells by 10%." }
                } },
                new Talent { TalentName = "Improved Prayer of Healing", ColumnIndex = 0, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "spell_holy_prayerofhealing02").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the Mana cost of your Prayer of Healing spell by 10%." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the Mana cost of your Prayer of Healing spell by 20%." }
                } },
                new Talent { TalentName = "Spirit of Redemption", ColumnIndex = 1, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "inv_enchant_essenceeternallarge").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Upon death, the priest becomes the Spirit of Redemption for 10 sec. The Spirit of Redemption cannot move, attack, be attacked or targeted by any spells or effects. While in this form the priest can cast any healing spell free of cost. When the effect ends, the priest dies." }
                } },
                new Talent { TalentName = "Spiritual Guidance", ColumnIndex = 2, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "spell_holy_spiritualguidence").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases spell damage and healing by up to 5% of your total Spirit." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases spell damage and healing by up to 10% of your total Spirit." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases spell damage and healing by up to 15% of your total Spirit." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases spell damage and healing by up to 20% of your total Spirit." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases spell damage and healing by up to 25% of your total Spirit." }
                } },
                new Talent { TalentName = "Spiritual Healing", ColumnIndex = 2, RowIndex = 5, TalentIconId = icons.First(i => i.FileName == "spell_nature_moonglow").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the amount healed by your healing spells by 2%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the amount healed by your healing spells by 4%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the amount healed by your healing spells by 6%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases the amount healed by your healing spells by 8%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases the amount healed by your healing spells by 10%." }
                } },
                new Talent { TalentName = "Lightwell", ColumnIndex = 1, RowIndex = 6, TalentIconId = icons.First(i => i.FileName == "spell_holy_summonlightwell").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Creates a holy Lightwell bear the priest. Members of your raid or party can click the Lightwell to restore 800 health over 10 sec. Being attacked cancels the effect. Lightwell lasts for 180 sec or 5 charges." }
                 } }
            };

            var shadowSpec = new List<Talent>
            {
                new Talent { TalentName = "Spirit Tap", ColumnIndex = 1, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "spell_shadow_requiem").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Gives you a 20% chance to gain a 100% bonus to your Spirit after killing a target that yields experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.." },
                        new TalentRank { RankNo = 2, RankDescription = "Gives you a 40% chance to gain a 100% bonus to your Spirit after killing a target that yields experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.." },
                        new TalentRank { RankNo = 3, RankDescription = "Gives you a 60% chance to gain a 100% bonus to your Spirit after killing a target that yields experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.." },
                        new TalentRank { RankNo = 4, RankDescription = "Gives you a 80% chance to gain a 100% bonus to your Spirit after killing a target that yields experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.." },
                        new TalentRank { RankNo = 5, RankDescription = "Gives you a 100% chance to gain a 100% bonus to your Spirit after killing a target that yields experience. For the duration, your Mana will regenerate at a 50% rate while casting. Lasts 15 sec.." }
                } },
                new Talent { TalentName = "Blackout", ColumnIndex = 2, RowIndex = 0, TalentIconId = icons.First(i => i.FileName == "spell_shadow_gathershadows").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Gives your Shadow damage spells a 10% chance to stun the target for 3 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Gives your Shadow damage spells a 10% chance to stun the target for 3 sec." },
                        new TalentRank { RankNo = 3, RankDescription = "Gives your Shadow damage spells a 10% chance to stun the target for 3 sec." }
                } },
                new Talent { TalentName = "Shadow Affinity", ColumnIndex = 0, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_shadow_shadowward").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the threat generated by your Shadow spells by 8%." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the threat generated by your Shadow spells by 16%." },
                        new TalentRank { RankNo = 3, RankDescription = "Reduces the threat generated by your Shadow spells by 25%." }
                } },
                new Talent { TalentName = "Improved Shadow Word: Pain", ColumnIndex = 1, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_shadow_shadowwordpain").Id,
                     TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the duration of your Shadow Word: Pain spell by 3 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the duration of your Shadow Word: Pain spell by 3 sec." }
                } },
                new Talent { TalentName = "Shadow Focus", ColumnIndex = 2, RowIndex = 1, TalentIconId = icons.First(i => i.FileName == "spell_shadow_burningspirit").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces your target's chance to resist your Shadow spells by 2%." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces your target's chance to resist your Shadow spells by 4%." },
                        new TalentRank { RankNo = 3, RankDescription = "Reduces your target's chance to resist your Shadow spells by 6%." },
                        new TalentRank { RankNo = 4, RankDescription = "Reduces your target's chance to resist your Shadow spells by 8%." },
                        new TalentRank { RankNo = 5, RankDescription = "Reduces your target's chance to resist your Shadow spells by 10%." }
                } },
                new Talent { TalentName = "Improved Psychic Scream", ColumnIndex = 0, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_shadow_psychicscream").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the cooldown of your Psychic Scream spell by 2 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the cooldown of your Psychic Scream spell by 4 sec." }
                } },
                new Talent { TalentName = "Improved Mind Blast", ColumnIndex = 1, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_shadow_unholyfrenzy").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Reduces the cooldown of your Mind Blast spell by 0.5 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Reduces the cooldown of your Mind Blast spell by 0.5 sec." },
                        new TalentRank { RankNo = 3, RankDescription = "Reduces the cooldown of your Mind Blast spell by 0.5 sec." },
                        new TalentRank { RankNo = 4, RankDescription = "Reduces the cooldown of your Mind Blast spell by 0.5 sec." },
                        new TalentRank { RankNo = 5, RankDescription = "Reduces the cooldown of your Mind Blast spell by 0.5 sec." }
                } },
                new Talent { TalentName = "Mind Flay", ColumnIndex = 2, RowIndex = 2, TalentIconId = icons.First(i => i.FileName == "spell_shadow_siphonmana").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Assault the target's mind with Shadow energy, causing 75 Shadow damage over 3 sec and slowing their movement speed 50%." }
                } },
                new Talent { TalentName = "Improved Fade", ColumnIndex = 1, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "spell_magic_lesserinvisibilty").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Decreases the cooldown of your Fade ability by 3 sec." },
                        new TalentRank { RankNo = 2, RankDescription = "Decreases the cooldown of your Fade ability by 6 sec." }
                } },
                new Talent { TalentName = "Shadow Reach", ColumnIndex = 2, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "spell_shadow_chilltouch").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the range of your Shadow damage spells by 6%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the range of your Shadow damage spells by 13%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases the range of your Shadow damage spells by 20%." }
                } },
                new Talent { TalentName = "Shadow Weaving", ColumnIndex = 3, RowIndex = 3, TalentIconId = icons.First(i => i.FileName == "spell_shadow_blackplague").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Your Shadow damage spells have a 20% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks up to 15001 times." },
                        new TalentRank { RankNo = 2, RankDescription = "Your Shadow damage spells have a 40% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks up to 15001 times." },
                        new TalentRank { RankNo = 3, RankDescription = "Your Shadow damage spells have a 60% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks up to 15001 times." },
                        new TalentRank { RankNo = 4, RankDescription = "Your Shadow damage spells have a 80% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks up to 15001 times." },
                        new TalentRank { RankNo = 5, RankDescription = "Your Shadow damage spells have a 100% chance to cause your target to be vulnerable to Shadow damage. This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec. Stacks up to 15001 times." }
                } },
                new Talent { TalentName = "Silence", ColumnIndex = 0, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "spell_shadow_impphaseshift").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Silence the target, preventing them from casting spells for 5 sec." }
                } },
                new Talent { TalentName = "Vampiric Embrace", ColumnIndex = 1, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "spell_shadow_unsummonbuilding").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Afflicts your target with Shadow energy that causes all party members to be healed for 20% of any Shadow spell damage you deal for 1 min." }
                } },
                new Talent { TalentName = "Improved Vampiric Embrace", ColumnIndex = 2, RowIndex = 4, TalentIconId = icons.First(i => i.FileName == "spell_shadow_improvedvampiricembrace").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases the percentage healed by Vampiric Embrace by an additional 5%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases the percentage healed by Vampiric Embrace by an additional 10%." }
                } },
                new Talent { TalentName = "Darkness", ColumnIndex = 2, RowIndex = 5, TalentIconId = icons.First(i => i.FileName == "spell_shadow_twilight").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Increases your Shadow spell damage by 2%." },
                        new TalentRank { RankNo = 2, RankDescription = "Increases your Shadow spell damage by 4%." },
                        new TalentRank { RankNo = 3, RankDescription = "Increases your Shadow spell damage by 6%." },
                        new TalentRank { RankNo = 4, RankDescription = "Increases your Shadow spell damage by 8%." },
                        new TalentRank { RankNo = 5, RankDescription = "Increases your Shadow spell damage by 10%." }
                } },
                new Talent { TalentName = "Shadowform", ColumnIndex = 1, RowIndex = 6, TalentIconId = icons.First(i => i.FileName == "spell_shadow_shadowform").Id,
                    TalentRanks = new List<TalentRank> {
                        new TalentRank { RankNo = 1, RankDescription = "Assume a Shadowform, increasing your Shadow damage by 15% and reducing Physical damage done to you by 15%. However, you may not cast Holy spells while in this form." }
                 } }
            };

            return new List<WarcraftClassSpecification> {
                new WarcraftClassSpecification { SpecificationName = "Discipline", SpecificationIndex = 0, SpecificationIcon = "spell_holy_wordfortitude.jpg", Talents = disciplineSpec },
                new WarcraftClassSpecification { SpecificationName = "Holy", SpecificationIndex = 1, SpecificationIcon = "spell_holy_holybolt.jpg", Talents = holySpec },
                new WarcraftClassSpecification { SpecificationName = "Shadow", SpecificationIndex = 2, SpecificationIcon = "spell_shadow_shadowwordpain.jpg", Talents = shadowSpec }
            };
        }

        public static void SetupTalentRequirements(List<WarcraftClassSpecification> wcs)
        {
            var disciplineTalents = wcs[0].Talents;
            var holyTalents = wcs[1].Talents;
            var shadowTalents = wcs[2].Talents;

            disciplineTalents.First(t => t.TalentName == "Divine Spirit").RequiredTalent = disciplineTalents.First(t => t.TalentName == "Meditation");
            disciplineTalents.First(t => t.TalentName == "Power Infusion").RequiredTalent = disciplineTalents.First(t => t.TalentName == "Mental Strength");

            holyTalents.First(t => t.TalentName == "Searing Light").RequiredTalent = holyTalents.First(t => t.TalentName == "Divine Fury");
            holyTalents.First(t => t.TalentName == "Lightwell").RequiredTalent = holyTalents.First(t => t.TalentName == "Spirit of Redemption");

            shadowTalents.First(t => t.TalentName == "Silence").RequiredTalent = shadowTalents.First(t => t.TalentName == "Improved Psychic Scream");
            shadowTalents.First(t => t.TalentName == "Improved Vampiric Embrace").RequiredTalent = shadowTalents.First(t => t.TalentName == "Vampiric Embrace");
            shadowTalents.First(t => t.TalentName == "Shadowform").RequiredTalent = shadowTalents.First(t => t.TalentName == "Vampiric Embrace");
        }
    }
}
